### ISSUE TITLE
[FEATURE] Limit IP access to the created site.

### ISSUE THREAD

**Issue by angelbarrera92** [angelbarrera92/mygit.website#1]
As a front-end developer I would like to use this project to temporarily deploy my developments to my clients. 
Some of my developments are private and should only be viewable from certain IP addresses.

To limit access you could add an attribute to the descriptor `.mygit.website` file:

```yaml
path: dist # The path where you have the website inside the repository
index: index.html # The index file
error: error.html # The error file
limits:
  ip:
  - 192.168.1.2
  - 10.0.1.2
  cidr:
  - 11.0.0.0/16
  - 192.168.0.0/24
```

This way you can limit access via IP or via CIDR.
